# Generated by Django 5.2.3 on 2025-06-19 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='secondary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='second/')),
                ('date_Added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('M', 'Mac'), ('L', 'Linux'), ('W', 'Windows')], max_length=1)),
            ],
        ),
    ]
